# options parameter for file with env variables. Remove if you don't need it
dotenv = '.env'
# transports configuration
[[transport]]
# The unique name of the transport
key = 'telegram_cosmos_proposals'
# transport type
type = 'telegram'
# telegram chat id. Put your chat id here. Can be channel or your id for direct messages
chat-id = '<id>'

# Networks configuration
[[network]]
# The unique name of the network (Required)
key = 'cosmos_mainnet'
# The chain id (Required)
chain-id = 'cosmoshub-4'
# The coin type (Required). This default value for most cosmos based networks. Check the your network docs to provide the correct value
hd-path = "m/44'/118'/0'/0/0"
# denom (Required)
denom = 'uatom'
# Address prefix (Required)
prefix = 'cosmos'
# Decimals (Required)
decimals = 6
wallet-key = ['my_wallet']
# RPC endpoints (Optional)
net = { rpc = ['https://rpc.cosmos.directory/cosmoshub'] }
# Lava protocol configuration (Optinal) 
lava = { chain = "COS5" }
# `lava` or `net`.One of this configuration is required 
# This will be used to create links to the block explorer. Links to proposals and trx result 
explorer = { proposal = 'https://www.mintscan.io/cosmos/proposals/:id', trx = 'https://www.mintscan.io/cosmos/txs/:hash' }
# Specify the transport to send notifications. Which is defined above (Required)
transport = 'telegram_cosmos_proposals'
